[package]
name = "executor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.15", features = ["derive"] }
hex-literal = "0.3.4"
jsonrpsee = { version = "0.15.1", features = ["ws-client", "macros"] }
serde = "1.0.136"
serde_json = "1.0"
tokio = { version = "1.21.2", features = ["full"] }

smoldot = { path = '../vendor/smoldot' }
