name: Deploy

on:
  push:
    branches: [ master ]

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26  # v3
        with:
          submodules: recursive
      - uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c  # v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            executor/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@be39649afda95dbf70f87cce95f68b8d5797b296  # nightly
        with:
          toolchain: nightly-2022-10-30
          components: rustfmt
          target: wasm32-unknown-unknown
      - name: Use Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610  # v3
        with:
          node-version: 18.x
          cache: 'yarn'
      - name: Build packages
        run: |
          yarn --immutable
          yarn check
          yarn build:web-test
      - name: Generate Docs
        run: |
          yarn docs:build
      - name: Setup Pages
        uses: actions/configure-pages@b8130d9ab958b325bbde9786d62f2c97a9885a0e  # v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@84bb4cd4b733d5c320c9c9cfbc354937524f4d64  # v1
        with:
          path: './dist'

  deploy:
    permissions:
      pages: write
      id-token: write
    needs: setup
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@f27bcc15848fdcdcc02f01754eb838e44bcf389b  # v1
